# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syspage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(max_length=30)),
                ('pageurl', models.CharField(max_length=30)),
                ('pagesort', models.IntegerField()),
                ('pagecreatedate', models.DateTimeField()),
                ('pagefatherid', models.IntegerField()),
                ('pagedeleteflag', models.IntegerField()),
            ],
        ),
    ]
